name: Run Docker Command

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  run-docker-command-1:
    runs-on: ubuntu-latest

    steps:
      - name: Run Dastardly Action Step
        uses: PortSwigger/dastardly-github-action@main
        with:
          target-url: 'https://ginandjuice.shop'

      - name: Publish Dastardly Scan Report
        if: always()
        uses: mikepenz/action-junit-report@v4
        with:
          check_name: 'Dastardly Scan Report'
          report_paths: '**/dastardly-report.xml'
          require_tests: true

