name: Run Commands

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  run-commands:
    runs-on: ubuntu-latest

    env:
      num1: 100          # Example value; replace with your actual value
      UA: "Mozilla/5.0 (Linux; Android 6.0.1; Nexus 5X Build/MMB29P) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/125.0.6422.66 Mobile Safari/537.36 (compatible; Googlebot/2.1; +http://www.google.com/bot.html)"  # Example value; replace with your actual user-agent
      METHOD: "GET"     # Example value; replace with your actual method
      URL: "https://testngwaf.global.ssl.fastly.net"  # Example value; replace with your actual URL

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Update APT and install uuid-runtime
      run: |
        sudo apt-get update
        sudo apt-get install uuid-runtime -y

    - name: Run curl commands
      run: |
        for i in $(seq 1 $num1); do
          curl -I -H "user-agent:$UA" -X$METHOD "$URL/$(uuidgen)"
        done
        echo "First job ran successfully"
