name: Run Docker Command
env:
  URL: "https://testngwaf.global.ssl.fastly.net"
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  run-docker-command:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Run Docker command
        uses: addnab/docker-run-action@v3
        with:
            image: abagayev/stop-russia:latest
            run: | 
                  bombardier -c 10000 -d 120s -l $URL
  

